# Generated by Django 2.0.13 on 2019-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='czytelnicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('haslo', models.CharField(max_length=45)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('data_urodzenia', models.DateTimeField(verbose_name='data urodzenia')),
                ('nr_telefonu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ksiazki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=45)),
                ('opis', models.CharField(max_length=45)),
                ('rok_wydania', models.DateTimeField(verbose_name='rok wydania')),
            ],
        ),
        migrations.CreateModel(
            name='wydawnictwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='wypozyczenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozycz', models.DateTimeField(verbose_name='data wypozyczenia')),
                ('data_oddania', models.DateTimeField(verbose_name='data oddania')),
            ],
        ),
    ]
